export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ACCOUNT_ROUTE = '/account'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'
export const ORDER_ROUTE = '/formorder'
export const ORDER_ITEM_ROUTE = '/order'
export const COURIER_ROUTE = '/courier'
export const COURIER_DELIVERY_ROUTE='/delivery'
export const ADMIN_ORDERS = '/adminorders'

